@host=https://localhost:9000
@token=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhhMGI0NDU2NThlOTcyZjAwZmQ0MGUiLCJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJlYTRhOWZhMjlkNTUxMDZmN2ViYTRiYWZhZWNiMThjNmViZGZhYmU5MDE5ZjRhNzYzYmIwY2Y5NTUzMWVkNDI5Iiwibmlja25hbWUiOiLotoXnuqfnrqHnkIblkZgiLCJzYWx0IjoiYWxpLXBheSIsImNvZGUiOiIiLCJkaXNhYmxlZCI6ZmFsc2UsInJvbGVzIjpbeyJfaWQiOiI2NjhhMGFhMDVhYjlmOWUxMTQ2NWMwZTMiLCJuYW1lIjoi6LaF57qn566h55CG5ZGYIiwiY29kZSI6ImFkbWluIiwicGNNZW51cyI6W3sibWVudSI6IioiLCJjcmVhdGUiOnRydWUsInJlYWQiOnRydWUsInVwZGF0ZSI6dHJ1ZSwiZGVsZXRlIjp0cnVlfV0sImFwcE1lbnVzIjpbXSwiaWQiOiI2NjhhMGFhMDVhYjlmOWUxMTQ2NWMwZTMifV0sInBjTWVudXMiOltdLCJhcHBNZW51cyI6W10sImlkIjoiNjY4YTBiNDQ1NjU4ZTk3MmYwMGZkNDBlIiwiaWF0IjoxNzIwOTYwODQwLCJleHAiOjE3MjA5NjQ0NDB9.C4L0ZctDtzG6cvXgAZ0uFE1ir4jSG6YQOY7l_ITuW_o

### 查询axios日志
POST {{host}}/api/axios_log/search_axios_log
Content-Type: application/json

{
  "deleted": false,
  "page": 1,
  "limit": 10,
  "sort": {
    "_id": 1
  }
}

### 创建axios日志
POST {{host}}/api/axios_log/create_axios_log
Content-Type: application/json
{{token}}

{

}

### 更新axios日志
POST {{host}}/api/axios_log/update_axios_log
Content-Type: application/json
{{token}}

{
  "_ids": [],
  "update": {

  }
}

### 软删除axios日志
POST {{host}}/api/axios_log/delete_axios_log
Content-Type: application/json
{{token}}

{
  "_ids": []
}

### 硬删除axios日志
POST {{host}}/api/axios_log/remove_axios_log
Content-Type: application/json
{{token}}

{
  "_ids": []
}
